spring:
  application:
    name: reactiveDemo
  r2dbc:
    url: r2dbc:h2:mem:///shopdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MySQL
    username: sa
    password: ""
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  sql:
    init:
      mode: always